apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: observability
data:
  config.alloy: |
    logging {
      level = "info"
    }

    otelcol.receiver.otlp "default" {
      grpc { endpoint = "0.0.0.0:4317" }
      http { endpoint = "0.0.0.0:4318" }
      
      output {
        traces = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        traces = [otelcol.exporter.otlp.tempo.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://tempo.observability.svc.cluster.local:4317"
        tls {
          insecure = true
        }
      }
    }

    pyroscope.write "pyro" {
      endpoint {
        url = "http://pyroscope.observability.svc.cluster.local:4040"
      }
    }

    loki.source.kubernetes "pods" {
      targets = [
        {
          "__address__" = "localhost",
          "__path__"    = "/var/log/pods/*/*/*.log",
        },
      ]
      forward_to = [loki.write.local.receiver]
    }

    loki.write "local" {
      endpoint {
        url = "http://loki.observability.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-alloy
  namespace: observability
spec:
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      serviceAccountName: grafana-alloy
      containers:
      - name: grafana-alloy
        image: grafana/alloy:v1.3.1
        args: ["run", "/etc/alloy/config.alloy"]
        volumeMounts:
        - name: config
          mountPath: /etc/alloy
        ports:
        - name: otlp-grpc
          containerPort: 4317
        - name: otlp-http
          containerPort: 4318
      volumes:
      - name: config
        configMap:
          name: alloy-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-alloy
  namespace: observability

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-alloy
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-alloy
subjects:
- kind: ServiceAccount
  name: grafana-alloy
  namespace: observability
